<?php

class Class_AH_Enqueue {
	
	
	public function __construct() {
		
		// Set up JS on schedule page
		add_action( 'wp_print_scripts', array( $this, 'setup_js_settings' ), 3 );
		add_action( 'admin_print_scripts', array( $this, 'setup_js_settings' ), 3 );
		
		// register scripts separately
		add_action( 'wp_enqueue_scripts', array( $this, 'register_scripts' ), 5 );
		add_action( 'admin_enqueue_scripts', array( $this, 'register_scripts' ), 5 );
		
		// enqueue what is needed
		add_action( 'wp_enqueue_scripts', array( $this, 'enqueue_frontend_scripts' ) );
		add_action( 'admin_enqueue_scripts', array( $this, 'enqueue_admin_scripts' ) );
		
	}
	
	/**
	 * Register all the assets we might use.
	 *
	 * @return void
	 */
	public function register_scripts() {
		
		$this->register( 'ah-api', 'api.js', array( 'jquery' ) );
		
		$this->register( 'ah-global', 'global.css' );
		$this->register( 'ah-global', 'global.js', array( 'jquery', 'ah-api' ) );
		
		$this->register( 'ah-admin', 'admin.css' );
		$this->register( 'ah-admin', 'admin.js', array( 'jquery', 'ah-global', 'ah-api' ) );
		
		$this->register( 'ah-public', 'public.css' );
		$this->register( 'ah-public', 'public.js', array( 'jquery', 'ah-global', 'ah-api' ) );
		
	}
	
	/**
	 * FRONTEND SCRIPTS
	 *
	 * @return void
	 */
	public function enqueue_frontend_scripts() {
		wp_enqueue_script( 'ah-api' );
		
		wp_enqueue_style( 'ah-global' );
		wp_enqueue_script( 'ah-global' );
		
		wp_enqueue_style( 'ah-public' );
		wp_enqueue_script( 'ah-public' );
	}
	
	/**
	 * ADMIN SCRIPTS
	 *
	 * @return void
	 */
	public function enqueue_admin_scripts() {
		wp_enqueue_script( 'ah-api' );
		
		wp_enqueue_style( 'ah-global' );
		wp_enqueue_script( 'ah-global' );
		
		wp_enqueue_style( 'ah-admin' );
		wp_enqueue_script( 'ah-admin' );
	}
	
	/**
	 * Returns the url to this plugin's assets folder:
	 * https://example.org/wp-content/plugins/aa-itineraries/assets/
	 *
	 * @param $filename
	 *
	 * @return string
	 */
	public function assets_url( $filename = '' ) {
		return AH_URL . '/assets/' . $filename;
	}
	
	/**
	 * Returns the local filesystem path to this plugin's assets directory:
	 * /var/www/example.org/wp-content/plugins/aa-itineraries/assets/
	 *
	 * @param $filename
	 *
	 * @return string
	 */
	public function assets_path( $filename = '' ) {
		return AH_PATH . '/assets/' . $filename;
	}
	
	/**
	 * Register a css or js file, but does not enqueue it
	 *
	 * @param $handle
	 * @param $filename
	 * @param $deps
	 * @param $enqueue
	 *
	 * @return void
	 */
	public function register( $handle, $filename, $deps = array(), $enqueue = false ) {
		$ext = pathinfo( $filename, PATHINFO_EXTENSION );
		$src = $this->assets_url($filename);
		$ver = filemtime($this->assets_path($filename));
		
		if ( $ext == 'css' ) {
			if ( $enqueue ) wp_enqueue_style( $handle, $src, $deps, $ver );
			else wp_register_style( $handle, $src, $deps, $ver );
		}else{
			if ( $enqueue ) wp_enqueue_script( $handle, $src, $deps, $ver );
			else wp_register_script( $handle, $src, $deps, $ver );
		}
	}
	
	/**
	 * Enqueue a css or js file so that it will be loaded
	 *
	 * @param $handle
	 * @param $filename
	 * @param $deps
	 *
	 * @return void
	 */
	public function enqueue( $handle, $filename, $deps = array() ) {
		$this->register( $handle, $filename, $deps, true );
	}
	
	/**
	 * Set up all our javascript objects after document has loaded
	 *
	 * @return void
	 */
	public function setup_js_settings() {
		remove_action( 'wp_print_scripts', array( $this, 'setup_js_settings' ), 3 );
		remove_action( 'admin_print_scripts', array( $this, 'setup_js_settings' ), 3 );
		
		$screen = function_exists('get_current_screen') ? (array) get_current_screen() : false;
		
		?>
		<script>
			// Settings generated by AH_Enqueue->setup_js_settings()
			// Used inside /assets/ah.js
			// These values are applied to the ah object, as ah.settings, for example: ah.settings.ajax.url
			window.ah_js_settings = {
				
				'is_admin': <?php echo json_encode(is_admin()); ?>,
				'debug_mode': <?php echo json_encode(aa_is_developer()); ?>,
				
				'admin': {
					// Values from WordPress's dashboard
					'ajaxurl':   window.ajaxurl   ? ajaxurl   : false,
					'adminpage': window.adminpage ? adminpage : false,
					'pagenow':   window.pagenow   ? pagenow   : false,
					'typenow':   window.typenow   ? typenow   : false,
				},

				'screen': {
					// post-new.php?post_type=ah_invoice == action: add, base: post, id: ah_invoice
					'action': <?php echo json_encode( $screen['action'] ?? false ); ?>,
					'base': <?php echo json_encode( $screen['base'] ?? false ); ?>,
					'id': <?php echo json_encode( $screen['id'] ?? false ); ?>,
					'post_type': <?php echo json_encode( $screen['post_type'] ?? false ); ?>,
					'taxonomy': <?php echo json_encode( $screen['taxonomy'] ?? false ); ?>,
				},

				'capabilities': {
					// 'read_schedule': <?php echo json_encode( current_user_can( 'read_schedule' ) ); ?>,
					// 'edit_schedule': <?php echo json_encode( current_user_can( 'edit_schedule' ) ); ?>,
				},
				
			};
		</script>
		<?php
		
	}
	
}